# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia_history', '0002_auto_20170510_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='ready',
            field=models.BooleanField(default=False),
        ),
    ]
