# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 01:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ia_history', '0008_auto_20170523_0130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='is_finished',
            new_name='finished',
        ),
    ]
