# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia_history', '0009_auto_20170523_0135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='finished',
        ),
        migrations.AddField(
            model_name='site',
            name='ready',
            field=models.BooleanField(default=False),
        ),
    ]
