# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 08:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia_history', '0010_auto_20170523_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 24, 8, 16, 10, 794910)),
        ),
    ]
