# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 15:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia_history', '0012_auto_20170525_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='request_date',
            field=models.DateTimeField(default=datetime.date(2017, 6, 2)),
        ),
    ]
